[pyprland]

plugins = [
  "scratchpads",
  "magnify",
  "expose"
]

[scratchpads.term]
animation = "fromTop"
command = "wezterm start --class wezterm-dropterm"
class = "wezterm-dropterm"
size = "50% 50%"